//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnChange.SG {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class templ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal templ() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnChange.SG.templ", typeof(templ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 // THIS IS AN AUTO-GENERATED FILE, DONT MODIFY IT!
        ///// Author: bbbirder
        ///// Defined Assembly: {{modulename}}
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Reflection;
        ///using com.bbbirder;
        ///{{ (target_namespace | string.empty) ? &quot;&quot; : &quot;namespace &quot;+target_namespace+&quot;{&quot; }}
        ///	public partial class {{target_name}}:IWatched{
        ///		IWatched _m__this = null;
        ///		IWatched __this=&gt;_m__this??=this;
        ///		public Action&lt;object, string, object, object&gt; onSetProperty { get; set; }
        ///		public Action&lt;object, string&gt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string classTemplate {
            get {
                return ResourceManager.GetString("classTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	private __private_{{name}};
        ///	public {{isStatic ? &quot;static&quot; : &quot;&quot;}} {{type}} {{name}} {
        ///		get {
        ///			__private_{{name}}??=DataWatcher.DataMaker.Reactive(__rawObject.{{name}});
        ///			onGetProperty?.Invoke(this,&quot;{{name}}&quot;);
        ///			return __private_{{name}};
        ///		}
        ///		set {
        ///			var prev = __private_{{name}};
        ///			__rawObject.{{name}} = value.__rawObject;
        ///			onSetProperty?.Invoke(this,&quot;{{name}}&quot;,value,prev);
        ///		}
        ///	} 的本地化字符串。
        /// </summary>
        public static string fieldGeneratedTemplate {
            get {
                return ResourceManager.GetString("fieldGeneratedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	{{access}} {{isStatic ? &quot;static&quot; : &quot;&quot;}} {{type}} {{name}} {
        ///		get {
        ///			onGetProperty?.Invoke(this,&quot;{{name}}&quot;);
        ///			return {{isStatic ? type : &quot;__rawObject&quot;}}.{{name}};
        ///		}
        ///		set {
        ///			var prev = __rawObject.{{name}};
        ///			{{isStatic ? type : &quot;__rawObject&quot;}}.{{name}} = value;
        ///			onSetProperty?.Invoke(this,&quot;{{name}}&quot;,value,prev);
        ///		}
        ///	} 的本地化字符串。
        /// </summary>
        public static string fieldTemplate {
            get {
                return ResourceManager.GetString("fieldTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 namespace com.bbbirder.onchange{
        ///	public partial class BaseWatched&lt;T&gt;{
        ///
        ///	}
        ///	
        ///}
        /// 的本地化字符串。
        /// </summary>
        public static string globalTemplate {
            get {
                return ResourceManager.GetString("globalTemplate", resourceCulture);
            }
        }
    }
}
