//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityVue.SG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnityVue.SG.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // NOTE: THIS IS AN AUTO-GENERATED FILE, NEVER MODIFY IT!
        ///// Generated by UnityVue
        ///// Author: bbbirder (labbbirder)
        ///// Assembly: {{module_name}}
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Reflection;
        ///using BBBirder.UnityVue;
        ///
        ///{{ (target_namespace | string.empty) ? &quot;&quot; : &quot;namespace &quot;+target_namespace+&quot;{&quot; }}
        ///
        ///{{~ for declaringType in declaring_types ~}}
        ///partial {{declaringType.keyword}} {{declaringType.name}} {
        ///{{~ end ~}}
        ///	partial class {{target_name}}
        ///	{
        ///		{{~ for m in membe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ExportFieldsTemplate {
            get {
                return ResourceManager.GetString("ExportFieldsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // NOTE: THIS IS AN AUTO-GENERATED FILE, NEVER MODIFY IT!
        ///// Generated by UnityVue
        ///// Author: bbbirder (labbbirder)
        ///// Assembly: {{module_name}}
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Reflection;
        ///using BBBirder.UnityVue;
        ///
        ///{{ (target_namespace | string.empty) ? &quot;&quot; : &quot;namespace &quot;+target_namespace+&quot;{&quot; }}
        ///
        ///{{~ for declaringType in declaring_types ~}}
        ///partial {{declaringType.keyword}} {{declaringType.name}} {
        ///{{~ end ~}}
        ///	partial class {{target_name}}
        ///	{
        ///		bool IWatchable.Is [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ImplementInterfaceTemplate {
            get {
                return ResourceManager.GetString("ImplementInterfaceTemplate", resourceCulture);
            }
        }
    }
}
